<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HangfireWorker-3b2a0693-04d9-4d90-bfca-18c483f2c989</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnonymousApi\AnonymousApi.csproj" />
    <ProjectReference Include="..\AnonymousApplication\AnonymousApplication.csproj" />
    <ProjectReference Include="..\AnonymousInfrastructure\AnonymousInfrastructure.csproj" />
  </ItemGroup>
</Project>
